const sparkle = document.createElement('rect')
sparkle.setAttribute('fill', '#ffc42e')
sparkle.setAttribute('width', '10')
sparkle.setAttribute('height', '10')

const star = document.createElement('rect')
star.setAttribute('fill', '#ffc42e')
star.setAttribute('width', '30')
star.setAttribute('height', '10')

export default function(wizard, frame) {
  // step 1
  if(frame % 4 == 0) {
    sparkle.setAttribute('x', '160')
    sparkle.setAttribute('y', '20')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
    star.setAttribute('x', '150')
    star.setAttribute('y', '30')
    wizard.childNodes[0].appendChild(star.cloneNode(true))
    sparkle.setAttribute('x', '160')
    sparkle.setAttribute('y', '40')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))

    sparkle.setAttribute('x', '140')
    sparkle.setAttribute('y', '60')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
    sparkle.setAttribute('x', '30')
    sparkle.setAttribute('y', '150')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
  } else if(frame % 4 == 1) {
    sparkle.setAttribute('x', '160')
    sparkle.setAttribute('y', '20')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
    star.setAttribute('x', '150')
    star.setAttribute('y', '30')
    wizard.childNodes[0].appendChild(star.cloneNode(true))
    sparkle.setAttribute('x', '160')
    sparkle.setAttribute('y', '40')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))

    sparkle.setAttribute('x', '140')
    sparkle.setAttribute('y', '60')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
    sparkle.setAttribute('x', '30')
    sparkle.setAttribute('y', '150')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
  } else if(frame % 4 == 2) {
    sparkle.setAttribute('x', '140')
    sparkle.setAttribute('y', '50')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
    star.setAttribute('x', '130')
    star.setAttribute('y', '60')
    wizard.childNodes[0].appendChild(star.cloneNode(true))
    sparkle.setAttribute('x', '140')
    sparkle.setAttribute('y', '70')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))

    sparkle.setAttribute('x', '30')
    sparkle.setAttribute('y', '140')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
    star.setAttribute('x', '20')
    star.setAttribute('y', '150')
    wizard.childNodes[0].appendChild(star.cloneNode(true))
    sparkle.setAttribute('x', '30')
    sparkle.setAttribute('y', '160')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))

    sparkle.setAttribute('x', '160')
    sparkle.setAttribute('y', '30')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
  } else if(frame % 4 == 3) {
    sparkle.setAttribute('x', '140')
    sparkle.setAttribute('y', '50')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
    star.setAttribute('x', '130')
    star.setAttribute('y', '60')
    wizard.childNodes[0].appendChild(star.cloneNode(true))
    sparkle.setAttribute('x', '140')
    sparkle.setAttribute('y', '70')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))

    sparkle.setAttribute('x', '30')
    sparkle.setAttribute('y', '140')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
    star.setAttribute('x', '20')
    star.setAttribute('y', '150')
    wizard.childNodes[0].appendChild(star.cloneNode(true))
    sparkle.setAttribute('x', '30')
    sparkle.setAttribute('y', '160')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))

    sparkle.setAttribute('x', '160')
    sparkle.setAttribute('y', '30')
    wizard.childNodes[0].appendChild(sparkle.cloneNode(true))
  }
  return wizard
}
